from pathlib import Path
from html import escape
import json,re
R=Path(__file__).resolve().parents[1]
LOC={'en':('','en'),'tc':('-zh-hk','zh-Hant'),'sc':('-zh-cn','zh-Hans')}
DATA={
'influencer-vs-community-building-2026':{
'en':{'title':'Influencer Marketing vs Community Building in 2026: Reach, Trust or Retention?','desc':'A 2026 framework for choosing influencer marketing, community building or a connected creator-to-community system.','facts':['Asian and Chinese brand teams, North American local businesses and growth leaders','F&B, beauty, retail, consumer brands and professional services','A brand gets creator views but little repeat purchase, referral or owned audience','Use when deciding whether budget should fund one-off KOL posts or a durable customer community'],'sections':[('Influence and community solve different problems','Influencer marketing borrows reach and trusted context. Community building creates a direct reason for customers to return, participate and refer. The choice should follow the broken stage of the customer journey, not the popularity of a tactic.'),('People this guide is for','This guide is for teams with campaign traffic but weak retention, and brands entering a new culture that need both credible introduction and an owned relationship.'),('Application scenario','A restaurant entering Canada can use local creators to demonstrate the first visit, then invite qualified customers into recurring tastings, member content or feedback programs. The creator opens the door; the community gives the relationship somewhere to continue.'),('Build the creator-to-community funnel','Match creators by audience and cultural relevance, give each post one measurable job, capture consented customer interest, deliver recurring value and use community questions to improve future briefs. Do not confuse a group chat with a community: participation needs a shared reason.'),('30/60/90-day plan','Days 1–30: diagnose reach, conversion and retention gaps. Days 31–60: test creators with a clear opt-in or repeat action. Days 61–90: measure qualified traffic, participation, second purchase, referral and retained members; scale the combination that compounds.'),('Evidence and measurement','IAB Canada says creator marketing is shifting from reach toward credible storytelling, measurable outcomes and always-on programs. Kantar identifies micro-communities as a major 2026 force. Measure the next behaviour, not impressions alone.')], 'sources':[('IAB Canada, 2026 creator marketing outlook','https://iabcanada.com/what-successful-creator-and-influencer-marketing-campaigns-look-like-in-canada/'),('Kantar Marketing Trends 2026','https://www.kantar.com/campaigns/marketing-trends')]},
'tc':{'title':'2026年網紅營銷 vs 社群建立：品牌需要的是觸及、信任，還是留存？','desc':'2026年品牌應如何選擇網紅營銷、社群建立，或建立相連的創作者至社群系統。','facts':['亞洲及中國品牌團隊、北美本地商戶與增長負責人','餐飲、美容、零售、消費品牌及專業服務','品牌有創作者觀看量，但欠缺回購、推薦及自有受眾','用於判斷預算應投放一次性KOL合作，還是可持續顧客社群'],'sections':[('網紅與社群解決不同問題','網紅營銷借用觸及及可信語境；社群建立則給顧客持續回來、參與及推薦的理由。品牌應按customer journey哪一環斷裂作決定，而非追逐熱門做法。'),('這篇指南針對甚麼人？','適合有campaign流量但留存薄弱的團隊，以及進入新文化、同時需要可信介紹與自有關係的品牌。'),('應用場景','一間進入加拿大的餐廳可先讓本地創作者示範首次體驗，再邀請合適顧客參與定期試食、會員內容或feedback program。創作者打開入口，社群讓關係延續。'),('建立Creator-to-Community Funnel','按受眾及文化相關性配對創作者，為每篇內容設定一個可量度任務，在取得同意下累積顧客關係，持續提供價值，再把社群問題用於改善下一輪brief。群組本身不等於社群，參與需要共同理由。'),('30／60／90日方案','首30日診斷觸及、轉換及留存缺口；第31–60日測試附帶清晰opt-in或回訪行動的creator內容；第61–90日量度有效流量、參與、第二次購買、推薦及留存。'),('證據與量度','IAB Canada指出creator marketing正由單純觸及轉向可信故事、可量度結果及always-on program；Kantar亦把micro-community列為2026重要趨勢。')], 'sources':[('IAB Canada：2026 Creator Marketing Outlook','https://iabcanada.com/what-successful-creator-and-influencer-marketing-campaigns-look-like-in-canada/'),('Kantar Marketing Trends 2026','https://www.kantar.com/campaigns/marketing-trends')]},
'sc':{'title':'2026年达人营销 vs 社群运营：品牌需要的是曝光、信任，还是留存？','desc':'2026年品牌应该如何选择达人营销、社群运营，或建立相连的达人到社群系统。','facts':['亚洲及中国品牌团队、北美本地商家与增长负责人','餐饮、美妆、零售、消费品牌和专业服务','品牌有达人播放量，却缺少复购、推荐和自有受众','用于判断预算应该投放一次性达人合作，还是可持续顾客社群'],'sections':[('达人与社群解决不同问题','达人营销借用曝光和可信场景；社群运营则给顾客持续回来、参与和推荐的理由。品牌应该根据顾客路径哪一环断裂做决定，而不是追逐热门做法。'),('这篇指南面向哪些人？','适合有campaign流量但留存薄弱的团队，以及进入新文化、同时需要可信介绍和自有关系的品牌。'),('应用场景','一家进入加拿大的餐厅可以先让本地达人示范首次体验，再邀请合适顾客参与定期试吃、会员内容或反馈计划。达人打开入口，社群让关系延续。'),('建立达人到社群的转化路径','按照受众和文化相关性匹配达人，为每篇内容设置一个可衡量任务，在取得同意后积累顾客关系，持续提供价值，再把社群问题用于改善下一轮brief。群聊本身不等于社群，参与需要共同理由。'),('30／60／90天方案','前30天诊断曝光、转化和留存缺口；第31–60天测试带有清晰opt-in或回访动作的达人内容；第61–90天衡量有效流量、参与、第二次购买、推荐和留存。'),('证据与衡量','IAB Canada指出creator marketing正从单纯曝光转向可信故事、可衡量结果和always-on program；Kantar也把micro-community列为2026重要趋势。')], 'sources':[('IAB Canada：2026 Creator Marketing Outlook','https://iabcanada.com/what-successful-creator-and-influencer-marketing-campaigns-look-like-in-canada/'),('Kantar Marketing Trends 2026','https://www.kantar.com/campaigns/marketing-trends')]}},
'ai-search-asian-brands-north-america-2026':{
'en':{'title':'What John Lewis’s AI Search Strategy Means for Asian Brands Entering North America in 2026','desc':'What John Lewis’s September 2026 AI-search content move teaches Asian brands about GEO, third-party trust and North America market entry.','facts':['North American consumers researching products through Google, YouTube, social platforms and AI assistants','Retail, F&B, beauty, lifestyle and e-commerce','An Asian brand has an English website and social posts but remains absent from AI recommendations and non-branded search','Use when building searchable, citable market-entry content rather than disconnected posts'],'sections':[('The September 2026 signal','On September 3, 2026, John Lewis announced a YouTube chatshow and social media studio intended to improve visibility across social and AI-driven search. The lesson is not that every brand needs a show; content is becoming searchable infrastructure.'),('People this guide is for','This matters to Asian brands entering North America whose customers compare products through search, video, reviews, creators and AI assistants before visiting or buying.'),('Application scenario','A Chinese beauty or food brand may have an English site and regular Instagram posts yet remain hard to understand outside branded searches. It needs content that states who the product serves, the occasion, local availability, proof and the next action.'),('From posts to an evidence network','Connect brand guides, creator demonstrations, customer questions, local reviews and third-party mentions. Consistency helps people and machines understand relevance; independent evidence reduces reliance on self-claims.'),('30/60/90-day plan','Days 1–30: audit branded and non-branded discovery plus missing questions. Days 31–60: publish people-industry-scenario guides and coordinate creator proof. Days 61–90: review AI mentions, citation accuracy, search visibility, qualified referrals and leads.'),('What GEO should not become','Do not create vague volumes of AI-written pages or promise chatbot citations. Build useful, verifiable content for customers first, keep technical access clean, and update claims when evidence changes.')], 'sources':[('The Guardian, September 3, 2026','https://www.theguardian.com/business/2026/sep/03/john-lewis-youtube-chat-show-angela-scanlon'),('Google Search Central: AI features and your website','https://developers.google.com/search/docs/appearance/ai-features')]},
'tc':{'title':'John Lewis為AI搜尋製作節目：2026年亞洲品牌進入北美可以學到甚麼？','desc':'John Lewis於2026年9月的AI搜尋內容策略，對亞洲品牌的GEO、第三方信任及北美市場拓展有何啟示。','facts':['使用Google、YouTube、社交平台及AI assistants研究產品的北美消費者','零售、餐飲、美容、生活方式及電商','亞洲品牌已有英文網站及社交內容，但很少出現在AI推薦及非品牌搜尋','用於建立可搜尋、可引用的市場進入內容，而非互不相連的帖文'],'sections':[('2026年9月的市場訊號','2026年9月3日，John Lewis宣布推出YouTube chatshow及social media studio，希望提升品牌在社交平台及AI搜尋的能見度。啟示不是每個品牌都要做節目，而是content正變成可搜尋的基礎設施。'),('這篇指南針對甚麼人？','適合進入北美的亞洲品牌；其顧客在購買或到店前，會同時參考搜尋、影片、評論、創作者及AI assistants。'),('應用場景','一個中國美容或食品品牌即使已有英文網站及定期Instagram內容，在非品牌搜尋下仍可能難以被理解。內容必須清楚交代服務誰、使用場合、本地供應、證據及下一步。'),('由帖文變成證據網絡','連接品牌指南、creator demonstration、顧客問題、本地評論及第三方mentions。一致資料協助人與機器理解相關性，獨立證據則減少只靠品牌自我宣稱。'),('30／60／90日方案','首30日審核品牌及非品牌搜尋與缺失問題；第31–60日發布people-industry-scenario指南並配合creator proof；第61–90日檢視AI mentions、引用準確度、搜尋能見度、有效referral及leads。'),('GEO不應變成甚麼','不要大量生產空泛AI文章，亦不要承諾一定獲chatbot引用。先為顧客建立實用、可驗證內容，保持technical access暢通，證據改變時更新主張。')], 'sources':[('The Guardian，2026年9月3日','https://www.theguardian.com/business/2026/sep/03/john-lewis-youtube-chat-show-angela-scanlon'),('Google Search Central：AI features','https://developers.google.com/search/docs/appearance/ai-features')]},
'sc':{'title':'John Lewis为AI搜索制作节目：2026年亚洲品牌进入北美可以学到什么？','desc':'John Lewis在2026年9月的AI搜索内容策略，对亚洲品牌的GEO、第三方信任和北美市场进入有何启示。','facts':['使用Google、YouTube、社交平台和AI助手研究产品的北美消费者','零售、餐饮、美妆、生活方式和电商','亚洲品牌已有英文网站和社交内容，却很少出现在AI推荐及非品牌搜索','用于建立可搜索、可引用的市场进入内容，而不是互不相连的帖子'],'sections':[('2026年9月的市场信号','2026年9月3日，John Lewis宣布推出YouTube访谈节目及社交媒体工作室，希望提升品牌在社交平台和AI搜索中的能见度。启示不是每个品牌都要做节目，而是内容正在成为可搜索的基础设施。'),('这篇指南面向哪些人？','适合进入北美的亚洲品牌；其顾客在购买或到店前，会同时参考搜索、视频、评价、达人和AI助手。'),('应用场景','一个中国美妆或食品品牌即使已有英文网站和定期Instagram内容，在非品牌搜索下仍可能难以被理解。内容必须清楚说明服务谁、使用场景、本地供应、证据和下一步。'),('从帖子变成证据网络','连接品牌指南、达人示范、顾客问题、本地评价和第三方提及。一致资料帮助人和机器理解相关性，独立证据则减少只靠品牌自我表述。'),('30／60／90天方案','前30天审核品牌及非品牌搜索与缺失问题；第31–60天发布people-industry-scenario指南并配合达人证据；第61–90天检查AI提及、引用准确度、搜索能见度、有效referral和leads。'),('GEO不应该变成什么','不要大量生产空泛AI文章，也不要承诺一定获得chatbot引用。先为顾客建立实用、可验证内容，保持technical access畅通，在证据变化时更新表述。')], 'sources':[('The Guardian，2026年9月3日','https://www.theguardian.com/business/2026/sep/03/john-lewis-youtube-chat-show-angela-scanlon'),('Google Search Central：AI features','https://developers.google.com/search/docs/appearance/ai-features')]}}
}
for base,langs in DATA.items():
 for loc,d in langs.items():
  sfx,lang=LOC[loc]; facts=['People','Industry','Scenario','Application'] if loc=='en' else (['目標人群','行業','場景','應用情況'] if loc=='tc' else ['目标人群','行业','场景','应用情况'])
  md=[f'# {d["title"]}','',d['desc'],'']+[f'**{k}:** {v}  ' for k,v in zip(facts,d['facts'])]+['**Year:** 2026' if loc=='en' else ('**年份：** 2026' if loc=='tc' else '**年份：** 2026'),'']
  for h,p in d['sections']:md += [f'## {h}','',p,'']
  md += ['## Sources','']+[f'- [{n}]({u})' for n,u in d['sources']]+['',('[Request a free audit](https://northiamarketing.com/index.html#contact)' if loc=='en' else '[申請免費品牌診斷](https://northiamarketing.com/index.html#contact)')]
  (R/f'{base}{sfx}.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
  alts=''.join(f'<link rel="alternate" hreflang="{code}" href="https://northiamarketing.com/{base}{sf}.html">' for sf,code in [('', 'en'),('-zh-hk','zh-Hant'),('-zh-cn','zh-Hans'),('','x-default')])
  sec=''.join(f'<section class="article-section{" audience-section" if i==1 else ""}"><h2>{escape(h)}</h2><p>{escape(p)}</p></section>' for i,(h,p) in enumerate(d['sections']))
  src='<section class="article-section evidence"><h2>Sources</h2><ul>'+''.join(f'<li><a href="{u}" rel="nofollow noopener" target="_blank">{escape(n)} ↗</a></li>' for n,u in d['sources'])+'</ul></section>'
  schema={'@context':'https://schema.org','@type':'Article','headline':d['title'],'description':d['desc'],'datePublished':'2026-09-03','dateModified':'2026-09-03','inLanguage':lang,'author':{'@type':'Organization','name':'Northia Marketing Consultancy Ltd.'},'mainEntityOfPage':f'https://northiamarketing.com/{base}{sfx}.html','audience':{'@type':'Audience','audienceType':d['facts'][0]}}
  tabs=f'<div class="language-tabs"><a class="{"on" if loc=="en" else ""}" href="{base}.html">EN</a><a class="{"on" if loc=="tc" else ""}" href="{base}-zh-hk.html">繁中</a><a class="{"on" if loc=="sc" else ""}" href="{base}-zh-cn.html">简中</a></div>'
  facthtml=''.join(f'<div><strong>{escape(k)}</strong><span>{escape(v)}</span></div>' for k,v in zip(facts,d['facts']))
  cta='Request a free audit' if loc=='en' else ('申請免費品牌診斷' if loc=='tc' else '申请免费品牌诊断')
  html=f'''<!DOCTYPE html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(d['title'])} | Northia</title><meta name="description" content="{escape(d['desc'])}"><link rel="canonical" href="https://northiamarketing.com/{base}{sfx}.html">{alts}<link rel="stylesheet" href="seo-pages.css"><link rel="alternate" type="text/markdown" href="/{base}{sfx}.md"><link rel="describedby" href="/llms.txt"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head><body><header class="header"><div class="wrap nav"><a class="brand" href="index.html"><img alt="" src="assets/northia-mark.png" width="38" height="38"><span>NORTHI<b>A</b></span></a><nav><a href="asia-to-world-marketing{sfx}.html">Asia to the World</a><a href="kol-influencer-marketing-asia{sfx}.html">KOL</a><a href="community-marketing-services{sfx}.html">Community</a></nav>{tabs}</div></header><main><article><section class="article-hero"><div class="wrap"><p class="eyebrow">2026 application guide</p><h1>{escape(d['title'])}</h1><p class="lead">{escape(d['desc'])}</p><div class="scenario-strip">{facthtml}</div></div></section><div class="wrap article-layout"><div class="article-body">{sec}{src}</div><aside class="article-aside"><h3>Northia</h3><a class="btn dark" href="index.html#contact">{cta}</a></aside></div></article></main><footer class="footer"><div class="wrap"><div class="copy">© 2026 Northia Marketing Consultancy Ltd.</div></div></footer></body></html>'''
  (R/f'{base}{sfx}.html').write_text(html,encoding='utf-8')

CARDS={
 'en':{
  'influencer':'''<article class="insight-card"><p class="article-meta">2026 GUIDE · Influencer + Community</p><h3><a href="influencer-vs-community-building-2026.html">Influencer Marketing vs Community Building in 2026</a></h3><p>Choose reach, trust or retention by the job your growth system needs to do.</p><a class="text-link" href="influencer-vs-community-building-2026.html">Read the guide →</a></article>''',
  'ai':'''<article class="insight-card"><p class="article-meta">2026 TREND · AI Search + Market Entry</p><h3><a href="ai-search-asian-brands-north-america-2026.html">What John Lewis’s AI Search Strategy Means for Asian Brands</a></h3><p>Turn market-entry content into a searchable evidence network for North American customers and AI assistants.</p><a class="text-link" href="ai-search-asian-brands-north-america-2026.html">Read the guide →</a></article>'''},
 'tc':{
  'influencer':'''<article class="insight-card"><p class="article-meta">2026指南 · 網紅營銷＋社群</p><h3><a href="influencer-vs-community-building-2026-zh-hk.html">2026年網紅營銷 vs 社群建立</a></h3><p>按品牌需要的觸及、信任或留存，選擇合適增長系統。</p><a class="text-link" href="influencer-vs-community-building-2026-zh-hk.html">閱讀指南 →</a></article>''',
  'ai':'''<article class="insight-card"><p class="article-meta">2026趨勢 · AI搜尋＋市場進入</p><h3><a href="ai-search-asian-brands-north-america-2026-zh-hk.html">John Lewis的AI搜尋策略對亞洲品牌有何啟示？</a></h3><p>把市場進入內容連成可搜尋、可驗證的北美證據網絡。</p><a class="text-link" href="ai-search-asian-brands-north-america-2026-zh-hk.html">閱讀指南 →</a></article>'''},
 'sc':{
  'influencer':'''<article class="insight-card"><p class="article-meta">2026指南 · 达人营销＋社群</p><h3><a href="influencer-vs-community-building-2026-zh-cn.html">2026年达人营销 vs 社群运营</a></h3><p>根据品牌需要的曝光、信任或留存，选择合适的增长系统。</p><a class="text-link" href="influencer-vs-community-building-2026-zh-cn.html">阅读指南 →</a></article>''',
  'ai':'''<article class="insight-card"><p class="article-meta">2026趋势 · AI搜索＋市场进入</p><h3><a href="ai-search-asian-brands-north-america-2026-zh-cn.html">John Lewis的AI搜索策略对亚洲品牌有何启示？</a></h3><p>把市场进入内容连成可搜索、可验证的北美证据网络。</p><a class="text-link" href="ai-search-asian-brands-north-america-2026-zh-cn.html">阅读指南 →</a></article>'''}
}

def add_to_grid(name, cards):
 p=R/name; s=p.read_text(encoding='utf-8')
 if all(re.search(r'href="([^"]+)"',card).group(1) in s for card in cards): return
 marker='</div>\n</div>\n</section>\n<section class="section consult-band">'
 if marker not in s: marker='</div>\n</div>\n</section>\n</main>'
 if marker not in s: raise RuntimeError(f'grid marker missing: {name}')
 s=s.replace(marker,'\n'.join(cards)+'\n'+marker,1)
 p.write_text(s,encoding='utf-8')

def add_section(name, lang, cards):
 p=R/name; s=p.read_text(encoding='utf-8')
 if all(re.search(r'href="([^"]+)"',card).group(1) in s for card in cards): return
 heading=('2026 application guides','Choose the next action by scenario.') if lang=='en' else (('2026應用指南','按實際場景選擇下一步。') if lang=='tc' else ('2026应用指南','按实际场景选择下一步。'))
 section=f'<section class="section insights-section"><div class="wrap"><div class="head"><p class="eyebrow">{heading[0]}</p><h2>{heading[1]}</h2></div><div class="insight-grid">'+''.join(cards)+'</div></div></section>\n'
 s=s.replace('</main>',section+'</main>',1)
 p.write_text(s,encoding='utf-8')

for lang,sfx in [('en',''),('tc','-zh-hk'),('sc','-zh-cn')]:
 if lang=='en':
  add_to_grid(f'kol-influencer-marketing-asia{sfx}.html',[CARDS[lang]['influencer']])
  add_to_grid(f'community-marketing-services{sfx}.html',[CARDS[lang]['influencer'],CARDS[lang]['ai']])
 else:
  add_section(f'kol-influencer-marketing-asia{sfx}.html',lang,[CARDS[lang]['influencer']])
  add_section(f'community-marketing-services{sfx}.html',lang,[CARDS[lang]['influencer'],CARDS[lang]['ai']])
 add_to_grid(f'asia-to-world-marketing{sfx}.html',[CARDS[lang]['ai']])

sitemap=R/'sitemap.xml'; s=sitemap.read_text(encoding='utf-8')
urls=[]
for base in DATA:
 for sfx,_ in LOC.values(): urls.append(f'  <url><loc>https://northiamarketing.com/{base}{sfx}.html</loc><lastmod>2026-09-03</lastmod></url>')
sitemap.write_text(s.replace('</urlset>','\n'.join(urls)+'\n</urlset>'),encoding='utf-8')

llms=R/'llms.txt'; s=llms.read_text(encoding='utf-8').rstrip()+'\n'
entries=[]
for base,langs in DATA.items():
 for lang,d in langs.items():
  sfx,_=LOC[lang]; entries.append(f'- [{d["title"]}](https://northiamarketing.com/{base}{sfx}.md)')
llms.write_text(s+'\n'+'\n'.join(entries)+'\n',encoding='utf-8')

t=R/'tests/test_static_agent_readiness.py'; s=t.read_text(encoding='utf-8')
s=s.replace("    'xiaohongshu-account-strategy-north-america-2026',\n]", "    'xiaohongshu-account-strategy-north-america-2026',\n    'influencer-vs-community-building-2026',\n    'ai-search-asian-brands-north-america-2026',\n]")
s=s.replace("'xiaohongshu-account-strategy-north-america-2026']", "'xiaohongshu-account-strategy-north-america-2026','influencer-vs-community-building-2026','ai-search-asian-brands-north-america-2026']")
t.write_text(s,encoding='utf-8')
